# Generated by Django 5.2.11 on 2026-04-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='croprecommendation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='crop_scans/'),
        ),
    ]
