# Generated by Django 5.2.11 on 2026-03-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
