"""
Django settings for crop_project project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY: Secret key loaded from .env (never hardcode this!)
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'fallback-key-change-in-production')

# SECURITY: Debug mode loaded from .env (set False in production!)
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# SECURITY: Allowed hosts loaded from .env
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'core',
    'homeapp',
    'predictor',
    'recommend',
    'chatbot',
    'soil',
    'analysis',
    'disease_detection',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crop_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crop_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static"
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ===========================================================
# 🔐 SECURITY HARDENING SETTINGS
# ===========================================================

# --- Clickjacking Protection ---
# Prevents your pages from being embedded in iframes on other sites
X_FRAME_OPTIONS = 'DENY'

# --- Content-Type Sniffing Protection ---
# Stops browsers from guessing MIME types (prevents drive-by downloads)
SECURE_CONTENT_TYPE_NOSNIFF = True

# --- XSS Filter ---
# Activates browser's built-in XSS filter
SECURE_BROWSER_XSS_FILTER = True

# --- Referrer Policy ---
# Controls how much URL info is sent with requests
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# --- File Upload Security ---
# Limit uploaded file size to 10MB to prevent DoS via large uploads
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024   # 10 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024   # 10 MB

# --- Session Security ---
# Expire sessions when browser closes
SESSION_COOKIE_AGE = 3600  # 1 hour in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# --- PRODUCTION-ONLY HTTPS Settings (uncomment when deploying with HTTPS) ---
# SECURE_SSL_REDIRECT = True            # Redirect all HTTP to HTTPS
# SESSION_COOKIE_SECURE = True          # Only send session cookie over HTTPS
# CSRF_COOKIE_SECURE = True             # Only send CSRF cookie over HTTPS
# SECURE_HSTS_SECONDS = 31536000        # Tell browsers to use HTTPS for 1 year
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True # Apply HSTS to all subdomains
# SECURE_HSTS_PRELOAD = True            # Allow browser HSTS preload lists
